Update xfst/foma scripts
git-svn-id: svn+ssh://svn.code.sf.net/p/hfst/code/trunk/hfst3@828 941e2c2b-deac-454f-805a-451daa25f33c

diff --git a/scripts/hfst-foma-wrapper.sh.in b/scripts/hfst-foma-wrapper.sh.in
--- a/scripts/hfst-foma-wrapper.sh.in
+++ b/scripts/hfst-foma-wrapper.sh.in
@@ -1,12 +1,12 @@
-#!/bin/sh
+#!/bin/bash
 foma_exec=@FOMACLI@
 if [ ! -x $foma_exec ] ; then
-    echo "$0 could not find foma from $foma_exec"
+    echo "$0 could not find executable foma from $foma_exec"
     exit 1
 fi
 
 function print_usage() {
-    echo "Usage: $0 [-h|-V] [-v|-s|-q] [-f FORMAT] [-F STACK_FILES]"
+    echo "Usage: $0 [-h|-V] [-v|-s|-q] [-f FORMAT] [-F STACK_FILES] [SCRIPTS]"
 }
 
 function print_help() {
@@ -19,9 +19,10 @@ function print_help() {
     echo "  -s   alias of -q"
     echo "  -f   select output format as HFST3 supported format names"
     echo "  -F   list files which xfst script saves as stacks that can be converted to HFST3 format"
+    echo "  -X   pass option string to foma verbatim"
     echo
-    echo "Input is read from stdin or free parameters of command line"
-    echo "Output is written to stdout"
+    echo "if SCRIPTS and input parameters from X are missing, stdin is used."
+    echo "Output is written to stdout."
     echo "If -f is omitted, HFST3 default is used"
     echo "If -F is omitted, we try to guess files to convert automatically"
 }
@@ -34,32 +35,33 @@ function print_version() {
     echo "There is NO WARRANTY, to the extent permitted by law."
 }
 
-while getopts "vqshVf:F:" flag ; do
+while getopts "vqshVf:F:X:" flag ; do
     case $flag in
-        h) print_help; exit 0;;
-        V) print_version; exit 0;;
-        v) verbose=-v;;
-        s,q) quiet=-q;;
-        f) format=-f $OPTARG;;
-        F) files=$OPTARG;;
-        ?) echo "Unknown command line switch $OPTARG, try -h for help"; print_usage; exit 1;;
+    h) print_help; exit 0;;
+    V) print_version; exit 0;;
+    v) verbose=-v;;
+    s|q) quiet=-q;;
+    f) format=-f $OPTARG;;
+    F) files=$OPTARG;;
+    X) fomaopts=$OPTARG;;
+    ?) echo "Unknown command line switch $OPTARG, try -h for help"; print_usage; exit 1;;
     esac
 done
 shift $(($OPTIND-1))
 if [ -z $@ ] ; then
     if [ "x$verbose" == "x-v" ] ; then
-        echo "running $foma_exec"
+        echo "running $foma_exec $fomaopts"
     fi
-    if ! $foma_exec ; then 
+    if ! $foma_exec $fomaopts; then 
         echo "$foma_exec failed"
         exit 1
     fi
 fi
 for f in $@ ; do
     if [ "x$verbose" == "x-v" ] ; then
-        echo "running $foma_exec -f $f"
+        echo "running $foma_exec $fomaopts -f $f"
     fi
-    if ! $foma_exec -f "$f" ; then
+    if ! $foma_exec $fomaopts -f "$f" ; then
         echo "$foma_exec -f $f failed"
         exit 1
     fi
@@ -67,14 +69,22 @@ done
 
 
 if [ -z $files ] ; then
-    for f in $@ ; do
-        files=$(egrep '^(save stack|ss)' $f | sed -e 's/.*\(save stack\|ss\) //') $files
+    if echo $fomaopts | grep -q '[-]f' ; then
+        scripts=$(echo $fomaopts | sed 's/[^ ]*-f \([^ ]*\).*/\1/') $scripts
+    fi
+    if echo $fomaopts | grep -q '[-]l' ; then
+        scripts=$(echo $fomaopts | sed 's/[^ ]*-l \([^ ]*\).*/\1/') $scripts
+    fi
+    for f in $@ $scripts; do
+        if egrep -q '^(save stack|ss)' "$f" ; then
+          files=$(egrep '^(save stack|ss)' < "$f" | sed -e 's/^save stack //' -e 's/^ss //') $files
+      fi
     done
     if [ "x$verbose" == "x-v" ] ; then
         echo "discovered stack files $files"
     fi
 fi
-if [ -z $files ] ; then
+if [ -z "$files" ] ; then
     echo "Unable to find saved stack files to convert; use -F!"
     exit 1
 fi
@@ -93,4 +103,4 @@ for f in $files ; do
     fi
     rm $f.tmpscript $f.att
 done
-
+# vim: set ft=bash
